version: 2
jobs:
    test:
        docker:
            - image: circleci/python:3.8.3
        steps:
            - checkout
            - run: ./setupenv.sh
            - run: |
                . env/bin/activate &&
                pytest
    deploy:
        docker:
            - image: circleci/buildpack-deps:stretch
              environment:
                IMAGE_NAME: wipac/docs-uploader
        steps:
            - checkout
            - setup_remote_docker
            - run: |
                echo 'export TAG="${CIRCLE_TAG:=latest}"' >> $BASH_ENV
            - run: |
                docker build -t $IMAGE_NAME:$TAG .
            - run: |
                echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
                docker push $IMAGE_NAME:$TAG
workflows:
    version: 2
    build_and_test:
        jobs:
            - deploy:
                context: docker
                filters:
                    branches:
                        only: master
    release:
        jobs:
            - deploy:
                context: docker
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /^v?\d+\.\d+\.\d+$/
